### ISSUE TITLE
[BUG]  asl to english

### ISSUE THREAD

**Issue by noob1234-afk** [sign/translate#150] opened 2024-03-17 16:32 UTC
### Current Behavior

when signing it doesn't put anything in the  text box

### Expected Behavior

when i sign it should put what i sign into the text box

### Steps To Reproduce

frist i swith the boxs so that the video box is on the left and then i wait for the camera to start and then started to sign.

### Example flow

```
paste your flow here
```

### Environment

- Device: (_eg._ iPhone Xs; laptop)
- OS: (_eg._ iOS 13.5; Fedora 32)
- Browser: (_eg._ Safari; Firefox)
- Version: (_eg._ 13; 73)
- Other info: (_eg._ display resolution, ease-of-access settings)

**Comment by AmitMY** [comment] 2024-03-19 08:16
Duplicate of #147

**Closed by AmitMY** 2024-03-19 08:16 UTC
Labels: bug
