### ISSUE TITLE
Generalizing Sign Language Segmentation Among Different Languages

### ISSUE THREAD

**Issue by 74Mazen74** [sign/translate#138] opened 2024-02-13 16:38 UTC
Concerning Sign Language Segmentation Stage, is the segmentation model general to any sign language?
if not,
What is the structure needed for the data to train my own segmentation model?
Thanks in advance!

**Comment by AmitMY** [comment] 2024-02-13 22:59
Duplicate of https://github.com/sign-language-processing/segmentation/issues/1

**Closed by AmitMY** 2024-02-13 22:59 UTC
