### ISSUE TITLE
[BUG] <Sekelton translation  is not  working>

### ISSUE THREAD

**Issue by Muhammadkamranlive** [sign/translate#38] opened 2022-04-29 04:56 UTC
### Current Behavior

remain loading not providing the translation of the text.

### Expected Behavior

The skeleton should show the translation of the text.

### Example flow

```
paste your flow here
```

### Environment

- Device: (_eg._ iPhone Xs; laptop)
- OS: (_eg._ iOS 13.5; Fedora 32)
- Browser: (_eg._ Safari; Firefox)
- Version: (_eg._ 13; 73)
- Other info: (_eg._ display resolution, ease-of-access settings)

**Comment by AmitMY** [comment] 2022-04-29 06:19
Hi @Muhammadkamranlive ,
It is not clear to me what you are attempting to do - could you perhaps include a screenshot?

**Comment by Muhammadkamranlive** [comment] 2022-05-05 06:13
> Hi @Muhammadkamranlive , It is not clear to me what you are attempting to do - could you perhaps include a screenshot?
Hy AmitMY @AmitMY 
**When I open your official site and start writing anything it just shows simple signs, not the actual skeleton animation,**
![image](https://user-images.githubusercontent.com/89290897/166870254-f4d843f0-bdfe-451b-a4f2-ebb46ff40aef.png)
![image](https://user-images.githubusercontent.com/89290897/166870423-9ce9bf9a-1801-4525-8963-ec7189d60854.png).

**it should be like this animation.**

![image](https://user-images.githubusercontent.com/89290897/166870697-7da40f06-6e38-43ca-958e-7bab40133f48.png)

I am remodifying the user interface and also added complete firebase authentication with google sign in also. Then I tested and realized animation is not working now more.

**Comment by AmitMY** [comment] 2022-05-06 17:05
Duplicate of #39 

Please note! Since you are modifying the software, your modification must also be distributed in GPL v3 license (see [here](https://github.com/sign/translate/blob/master/LICENSE))

Adding firebase authentication was actually done by me already, in a different fork of this project, which will be available at some point in the near future.

**Closed by AmitMY** 2022-05-06 17:05 UTC
Labels: bug
