### ISSUE TITLE
[BUG] <txt to sign>

### ISSUE THREAD

**Issue by Karim-Errahem** [sign/translate#195] opened 2024-12-29 01:32 UTC
### Current Behavior

the sign to text transition always show "what is your name" only.

### Example flow

```
paste your flow here
```

### Environment

- Device: (_eg._ iPhone Xs; laptop)
- OS: (_eg._ iOS 13.5; Fedora 32)
- Browser: (_eg._ Safari; Firefox)
- Version: (_eg._ 13; 73)
- Other info: (_eg._ display resolution, ease-of-access settings)

**Comment by AmitMY** [comment] 2024-12-29 10:36
duplicate of #174

**Closed by AmitMY** 2024-12-29 10:36 UTC
Labels: bug
